version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    restart: always
    container_name: "rumble-tg"
    volumes:
      - rumble_volume:/app


volumes:
  rumble_volume: