# Generated by Django 4.2.3 on 2023-08-11 12:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_id', models.CharField(max_length=56, primary_key=True, serialize=False, unique=True, verbose_name='Telegram chat id')),
                ('first_name', models.CharField(default='Нет информации', max_length=56, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(default='Нет информации', max_length=56, verbose_name='Фамилия пользователя')),
                ('username', models.CharField(default='Нет информации', max_length=56, verbose_name='Имя аккаунта TG')),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время и дата первого запроса')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Janras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Moderators',
            fields=[
                ('chat_id', models.CharField(max_length=56, primary_key=True, serialize=False, unique=True, verbose_name='Telegram chat id')),
                ('name', models.CharField(default='none', max_length=56, verbose_name='ФИО модератора')),
                ('last_callback', models.CharField(default={'callback': 'none'}, max_length=56, verbose_name='Последний callback')),
                ('last_id', models.CharField(default={'callback': 'none'}, max_length=56, verbose_name='Последний callback ID')),
                ('first_name', models.CharField(default='Нет информации', max_length=56, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(default='Нет информации', max_length=56, verbose_name='Фамилия пользователя')),
                ('username', models.CharField(default='Нет информации', max_length=56, verbose_name='Имя аккаунта TG')),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время и дата первого запроса')),
            ],
            options={
                'verbose_name': 'Модератор',
                'verbose_name_plural': 'Модераторы',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Файл без названия', max_length=56, verbose_name='Название')),
                ('tg_id', models.CharField(max_length=256, verbose_name='ID в телеграмме')),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время и дата создания')),
                ('moderator_id', models.CharField(max_length=56, verbose_name='id модератора')),
                ('foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artists')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.AddField(
            model_name='artists',
            name='foreign_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.janras'),
        ),
    ]
