# Generated by Django 4.2.3 on 2023-08-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='foreign_key',
            new_name='janra',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='foreign_key',
            new_name='artist',
        ),
    ]
