# Generated by Django 4.2.3 on 2023-08-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chats_last_callback_chats_last_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterField(
            model_name='chats',
            name='last_callback',
            field=models.CharField(default={'callback': 'none'}, max_length=56, verbose_name='Последний callback'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='last_id',
            field=models.CharField(default={'callback': 'none'}, max_length=56, verbose_name='Последний callback ID'),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(default='Файл без названия', max_length=56, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='moderators',
            name='last_callback',
            field=models.CharField(default={'callback': 'none'}, max_length=56, verbose_name='Последний callback'),
        ),
        migrations.AlterField(
            model_name='moderators',
            name='last_id',
            field=models.CharField(default={'callback': 'none'}, max_length=56, verbose_name='Последний callback ID'),
        ),
    ]
