# Generated by Django 4.2.3 on 2023-08-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='def_name',
            field=models.CharField(max_length=56, verbose_name='Имя функции'),
        ),
    ]
